---

- hosts: lemp
  remote_user: admin1
  become: yes
  module_defaults:
    mysql:
      login_unix_socket: /var/run/mysqld/mysqld.sock
#      config_file: /etc/mysql/my.cnf
#      login_user: root
#      login_password: ""
#      check_implicit_admin: true
  
  roles:
    - common
    - web
    - db

